# Copy to secrets.toml when you're ready to sync to Snowflake.
# [snowflake]
# account = "xxxxxx"
# user = "xxxxxx"
# password = "xxxxxx"
# warehouse = "xxxxxx"
# database = "xxxxxx"
# schema = "xxxxxx"
